version: "3.9"

services:
  auth:
    build: .
    container_name: auth_service
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    external: true
