name: Deploy Auth Service to Cloud Run

on:
  push:
    branches: ["ranting"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker auth
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          IMAGE="asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ranting-repo/auth-service:latest"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE="asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ranting-repo/auth-service:latest"
          gcloud run deploy auth-service \
            --image $IMAGE \
            --region asia-southeast2 \
            --platform managed \
            --cpu 1 \
            --memory 512Mi \
            --concurrency 80 \
            --min-instances 0 \
            --max-instances 3 \
            --allow-unauthenticated

